# LaBSE

In [1]:
from transformers import BertForPreTraining, BertTokenizer, BertTokenizerFast, BertConfig, AutoModel, AutoTokenizer

In [2]:
labse_ba_path = '../models/LaBSE-distilled-bak'

In [4]:
labse_ba_tokenizer = AutoTokenizer.from_pretrained(labse_ba_path)
labse_ba_model = BertForPreTraining.from_pretrained(labse_ba_path)

In [7]:
push_name = 'slone/LaBSE-shallow-distilled-bak'

In [8]:
labse_ba_model.push_to_hub(push_name)

CommitInfo(commit_url='https://huggingface.co/slone/LaBSE-shallow-distilled-bak/commit/4b7f595e35039bd602ceb91642ddd103c7ba7066', commit_message='Upload BertForPreTraining', commit_description='', oid='4b7f595e35039bd602ceb91642ddd103c7ba7066', pr_url=None, pr_revision=None, pr_num=None)

In [9]:
labse_ba_tokenizer.push_to_hub(push_name)

CommitInfo(commit_url='https://huggingface.co/slone/LaBSE-shallow-distilled-bak/commit/eb467572b9c33613cdc9e8c6a6d559eace23749b', commit_message='Upload tokenizer', commit_description='', oid='eb467572b9c33613cdc9e8c6a6d559eace23749b', pr_url=None, pr_revision=None, pr_num=None)

# Classifier

In [3]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [4]:
clf_path = '../models/bak-ru-combined'

In [5]:
model = AutoModelForSequenceClassification.from_pretrained(clf_path)

In [6]:

tokenizer = AutoTokenizer.from_pretrained(clf_path)

In [7]:
push_name = 'slone/bert-base-multilingual-cased-bak-rus-similarity'

In [8]:
model.push_to_hub(push_name)

CommitInfo(commit_url='https://huggingface.co/slone/bert-base-multilingual-cased-bak-rus-similarity/commit/9ab919dcb7ddb3fa1d142426ace7ff23374db675', commit_message='Upload BertForSequenceClassification', commit_description='', oid='9ab919dcb7ddb3fa1d142426ace7ff23374db675', pr_url=None, pr_revision=None, pr_num=None)

In [9]:
tokenizer.push_to_hub(push_name)

CommitInfo(commit_url='https://huggingface.co/slone/bert-base-multilingual-cased-bak-rus-similarity/commit/46bd8a23a62e7d034e8fb4cf683d6e9868cd56eb', commit_message='Upload tokenizer', commit_description='', oid='46bd8a23a62e7d034e8fb4cf683d6e9868cd56eb', pr_url=None, pr_revision=None, pr_num=None)

# Test it

In [1]:
import torch
from transformers import AutoModel, AutoTokenizer
model = AutoModel.from_pretrained('slone/LaBSE-shallow-distilled-bak')
tokenizer = AutoTokenizer.from_pretrained('slone/LaBSE-shallow-distilled-bak')

def embed(texts, max_length=512):
    b = tokenizer(texts, return_tensors='pt', padding=True, truncation=True, max_length=max_length)
    with torch.inference_mode():
        return torch.nn.functional.normalize(model(**b.to(model.device)).pooler_output).cpu().numpy()

Downloading:   0%|          | 0.00/643 [00:00<?, ?B/s]

c:\users\david\appdata\local\programs\python\python39\lib\site-packages\huggingface_hub\file_download.py:127: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\david\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Downloading:   0%|          | 0.00/169M [00:00<?, ?B/s]

Some weights of the model checkpoint at slone/LaBSE-shallow-distilled-bak were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/362 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/444k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/960k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [4]:
embeddings = embed(['Сәләм, ғаләм!', 'Хәйерле көн, тыныслыҡ.', 'Бөгөн йома.'])

In [8]:
print(embeddings.shape)
print(embeddings.dot(embeddings.T).round(2))

(3, 768)
[[1.   0.56 0.18]
 [0.56 1.   0.32]
 [0.18 0.32 1.  ]]


In [10]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
path = 'slone/bert-base-multilingual-cased-bak-rus-similarity'
model = AutoModelForSequenceClassification.from_pretrained(path)
tokenizer = AutoTokenizer.from_pretrained(path)

Downloading:   0%|          | 0.00/843 [00:00<?, ?B/s]

c:\users\david\appdata\local\programs\python\python39\lib\site-packages\huggingface_hub\file_download.py:127: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\david\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Downloading:   0%|          | 0.00/711M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/357 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.92M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/125 [00:00<?, ?B/s]

# Test another

In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

clf_name = 'slone/bert-base-multilingual-cased-bak-rus-similarity'
clf = AutoModelForSequenceClassification.from_pretrained(clf_name)
clf_tokenizer = AutoTokenizer.from_pretrained(clf_name)

def classify(texts_ba, texts_ru):
    with torch.inference_mode():
        batch = clf_tokenizer(texts_ba, texts_ru, padding=True, truncation=True, max_length=512, return_tensors='pt').to(clf.device)
        return torch.softmax(clf(**batch).logits.view(-1, 2), -1)[:, 1].cpu().numpy()

In [7]:
print(classify(['Сәләм, ғаләм!', 'Хәйерле көн, тыныслыҡ.'], ['Привет, мир!', 'Мама мыла раму.']))

[0.96345973 0.02213471]


In [6]:
print(classify(
    ['Сәләм, ғаләм!', 'Сәләм, ғаләм!', 'Сәләм, ғаләм!',], 
    ['Привет, мир!', 'Прощай, вселенная!', 'Мама мыла раму.']
))

[0.96345973 0.9459178  0.00889423]
